name: furnishop
description: A production-like Flutter furniture e-commerce app following Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Networking & Serialization
  http: ^1.1.2
  dio: ^5.4.0
  json_annotation: ^4.8.1

  # Routing
  go_router: ^13.0.1

  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.3.1

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  # Testing
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
